name: CI/CD to EC2

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@16.16.208.98 << 'EOF'
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker pull sherinmonbiju/flask-app
          docker run -d -p 5000:5000 sherinmonbiju/flask-app
        EOF
